worker_processes auto;

events {
    use epoll;
    worker_connections 1024;
}

http {
    upstream minio {
        server 127.0.0.1:9000;
    }

    # HTTP/1
    server {
        listen 8080;
        server_name _;
    
        client_max_body_size 0;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;

            proxy_pass http://minio;
        }
    }

    # HTTP/1 with SSL
    server {
        listen 8090 ssl;
        server_name _;

        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        ssl_protocols TLSv1.3;

        client_max_body_size 0;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;

            proxy_pass http://minio;
        }
    }

    # HTTP/2
    server {
        listen 8443 ssl http2;
        server_name _;

        ssl_protocols TLSv1.3;
        ssl_early_data on;

        http2 on;

        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        client_max_body_size 0;
        proxy_buffering off;
        ignore_invalid_headers off;
    
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log debug;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;

            proxy_pass http://minio;
        }
    }

    # HTTP/3
    server {
        listen 9000 quic reuseport;
        server_name _;

        ssl_protocols TLSv1.3;
        ssl_early_data on;
        quic_gso on;
        http3 on;
        add_header Alt-Svc 'h3=":443"; ma=86400' always;

        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        client_max_body_size 0;
        proxy_buffering off;
        ignore_invalid_headers off;
    
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log debug;

        location / {
            proxy_set_header Host "$host:$server_port";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;

            proxy_pass http://minio;
        }
    }
}
